/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.2.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as board from "../board";
import type * as boards_mutations from "../boards/mutations";
import type * as boards_queries from "../boards/queries";
import type * as column from "../column";
import type * as columns_mutations from "../columns/mutations";
import type * as columns_queries from "../columns/queries";
import type * as task from "../task";
import type * as tasks_mutations from "../tasks/mutations";
import type * as tasks_queries from "../tasks/queries";
import type * as type from "../type";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  board: typeof board;
  "boards/mutations": typeof boards_mutations;
  "boards/queries": typeof boards_queries;
  column: typeof column;
  "columns/mutations": typeof columns_mutations;
  "columns/queries": typeof columns_queries;
  task: typeof task;
  "tasks/mutations": typeof tasks_mutations;
  "tasks/queries": typeof tasks_queries;
  type: typeof type;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
