import "./globals.css";
import { useEffect } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Appbar from "@/components/appbar";
import ScrollProgress from "@/components/scroll-progress";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="bg-white dark:bg-slate-900">
            <ScrollProgress />
            <Appbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
